[profile.release]
panic = 'unwind'

[workspace]
members = [
    'common',
    'executor',
    'node',
    'pallets/capsules',
    'pallets/marketplace',
    'pallets/timed-escrow',
    'primitives',
    'runtime',
]